language: go
sudo: false

go:
  - 1.5
  - 1.5.1
  - tip

env:
  - GO15VENDOREXPERIMENT=1

install:
  - go install

script:
  - go vet -v $(go list ./...|grep -v vendor)
  - go test -v $(go list ./...|grep -v vendor)
  - rm -rf vendor
  - govend -v
  - go install
