language: go

go:
  - 1.5
  - 1.5.1
  - tip

env:
  - GO15VENDOREXPERIMENT=1

install:
  - go install
  - govend -v

script:
  - go vet -v $(go list ./...|grep -v vendor)
  - go test -v $(go list ./...|grep -v vendor)
